SELECT Y.AGE, Y.FREQ AS FREQY, N.FREQ AS FREQN FROM
(SELECT YN, AGE, COUNT(ID) AS FREQ
FROM CHALLENGE WHERE YN='Y'
GROUP BY AGE, YN) AS Y
JOIN
(SELECT YN, AGE, COUNT(ID) AS FREQ
FROM CHALLENGE WHERE YN='N'
GROUP BY AGE, YN) AS N
ON Y.AGE=N.AGE;
\q