CREATE TABLE TEST2(
ID SERIAL PRIMARY KEY,
YN VARCHAR(2),
AGE SMALLINT,
BIRTHDAY VARCHAR(16),
BOOL VARCHAR(8),
CITY VARCHAR(30),
CCNUMBER BIGINT,
DATE DATE,
DIGIT NUMERIC,
DOLLAR varchar(20),
FIRST VARCHAR(50),
CHIFRE NUMERIC,
NAME VARCHAR(50),
LAST VARCHAR(50),
PARAGRAPH TEXT,
SENTENCE TEXT
);