CREATE TABLE CHALLENGE(
ID SERIAL PRIMARY KEY,
YN VARCHAR(2),
AGE SMALLINT,
BIRTHDAY DATE,
BOOL BOOL,
CITY VARCHAR(30),
CCNUMBER NUMERIC,
DATE DATE,
DIGIT NUMERIC,
DOLLAR MONEY,
FIRST VARCHAR(50),
CHIFRE NUMERIC,
NAME VARCHAR(50),
LAST VARCHAR(50),
PARAGRAPH TEXT,
SENTENCE TEXT
);

--AFTER IMPORTING DATA, RESET VALUE OF 

ALTER SEQUENCE challenge_id_seq RESTART WITH 1000001